### ISSUE TITLE
Milestone 2 

### ISSUE THREAD

**Issue by roanraina** [UBC-MDS/diabetes_prediction#21]
TO DO:

Part 1) Analysis code is abstracted to four (or more) scripts: 

- [x] Script to download data from the internet and save it locally
    - @roanraina 
- [x] Script that reads the data and performs and data cleaning/pre-processing, transforming, and/or partionting that needs to happen before exploratory data analysis or modeling takes place
    - @roanraina 
- [x] Script which creates exploratory data visualization(s) and table(s) that are useful to help the reader/consumer understand that dataset.
    - @austin-shih 
- [x] Script that reads the data from the second script, performs some statistical or machine learning analysis and summarizes the results as a figure(s) and a table(s).
    - @austin-shih 
- [x] an .Rmd or .ipynb files that presents the key useful (not all!) exploratory data analysis as well as the statistical summaries and figures in a little report.
    - @florawendy19 and @mehdi-naji

Part 2) Version control
- done as team members make contributions via GitHub
 
Part 3) Project organization and documentation expectations:
- [x] @roanraina 

Submission:
- @austin-shih to create release, close issue, and submit by Nov 26, 2022 @ 6pm 

Feel free to discuss questions about this milestone in the comments below.

**Comment by roanraina** [comment]
Milestone 2 completed and submitted to canvas. Closing issue.
