### ISSUE TITLE
Milestone 1 - Feedback

### ISSUE THREAD

**Issue by danielramandi** [UBC-MDS/diabetes_prediction#26]
Congratulations on finishing milestone 1! We can see you put a lot of work into this project, nice work! Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project. 

**1. Code of Conduct.md**

- [ ] A Statement on diversity and inclusivity -1

**Comment:** This is an important section and I highly suggest adding it to your CofC.

**2. CONTRIBUTING.md** 

- [ ] Contributing documentation should reflect all the ways people can contribute to the project (core members, who should be working in a GitHub flow workflow involving branching in the main project repo and opening PR's, as well as arms-length contributors, who are more likely may have to fork the repo before submitting a PR). -2

**Comment:** I suggest adding more details on the ways of contribution and the process. Some parts are either unclear or not detailed enough.
**3. Project proposal**

- [ ] The clarity of README could be improved through additional proofreading (i.e., spelling and grammatical errors are present). -1

**4. Exploratory data analysis in a literate code document**

- [ ] Plots suffer from one or more severe problems. For instance, overplotting, missing legend, small text, or no axis labels. -2 viz

**Comment:** The histograms are hard to read. This is due to the scaling of the x-axis. I suggest trying to widen the bars by modifying the bins.

- [ ] There are no figure captions. -2 viz

- [ ] The captions for the tables should be above the table. -1 viz

**Comment:** Adding figure and table captions and subplot titles can make it easy to understand the figures/tables and also refer to them in the text.

- [ ] There are no references in the analysis (.ipynb or .Rmd) file -2

**Comment: I** suggest making your file more modular, so it would be easier to follow the flow of analysis and key findings.

- [ ] The narration of methods and method choices was not as clear and thorough as expected. -1

**Comment:** The explanation of the data cleaning process is not clear or provided. This is part is very important, as untransparent data-cleaning strategies can heavily affect the reproducibility of the analysis.

- [ ] The text is difficult to understand. Clarity could be improved. There are many typos, the text is difficult to read. -2 writing

**Comment:** The clarity of the project can be influenced by the quality of the writing. Inconsistent tone, grammatical inaccuracies, and spelling errors can disengage the reader. I suggest keeping a semi-formal or neutral tone (avoid contractions, etc.), and proofreading. You can use Grammarly as a tool to check your writing.

5. Expectations

- [ ] All the team members should have meaningful commits to the project -5

**Comment:** The contributors listed by GitHub are lacking a member. Also, the number of commits is very variable between group participants. If this is how you divided your project load, please be more specific about it on the teamwork contract.

**Overall comment:** The project is well designed and the dataset is chosen wisely to fit the project. The question is clear and the structure of the repo looks good. However, in order to improve and clarify the codes, scripts, reports, and documentation, more effort should be put into the proofreading process. I suggest having clear modules and sections in your reports and keeping a flow of the pipeline so that it is easy to follow and understand. Oversectioning the report also should be avoided. I suggest designing a frame for your report and building it up. eg. Intro, Data, Cleaning, EDA, etc.). In this example, EDA would have subsections for feature value distributions and feature correlations.
