### ISSUE TITLE
Milestone 2 Comment

### ISSUE THREAD

**Issue by Glenn032787** [UBC-MDS/diabetes_prediction#34]
Congratulations on finishing milestone 2! We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.

We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.

#### 1.1 Analysis code is abstracted to four (or more) scripts which take command line arguments and save analysis artifacts (e.g., figures and data for tables).
- [ ] Code in one or more scripts is not of high quality, or does not adhere to the adopted code styles for the course: author, date and where the script has been extracted from (if it is a re-used script), should be added **-1**  **quality**
**Comment:** Author and date missing from download_data.py

#### 1.2 Report is written in a literate code document, and the code in the literate code document primarily functions to source analysis artifacts and format the document.

- [ ] The `proposal.md` file has been created and moved to the `doc` directory **-2** **mechanics**

- [ ] There are not figure captions. **-1** **viz**
**Comment:** Figure captions are not shown in the knitted version of the Rmd. fig.cap paramters is included in the image header.

### 1.3 Code is abstracted to functions with good function design

 
- [ ] There are cases of functions that are too big and could be improved by defining utility functions. **-1** **reasoning**
**Comments:** Make sure to split the main() function into smaller functions to improve readibility. 
  
  
  
   
### 1.4 Functions are well documented
- [ ] One or more functions are only partially understood from reading their documentation. **-2** **quality**
**Comment:** Documentation and purpose of some functions were not clear (ie  pipe(model)). Make sure to use consistent documentation style (including explain what each variables are) for every function defined. 
#### 1.5 Code is called in the analysis

Good job!

---

##### From these 7 points remove points if:

- [ ] There are cases of functions with tests that fail. **-3** **accuracy**

- [ ] There is no documentation. It is not clear what the tests are testing. **-2** **quality**

- [ ] There is commented out code. **-1** **quality**
**Comment:** Test were not added with testthat or pytest. However, it is good that some assertions were added in the code.
---

#### 1.9 Dependencies have been updated (so it include the test libraries)
Good job!

#### 2.1 GitHub Issues

Good job!

#### 2.2 Follows GitHub flow version control workflow
Good job!

### 3.1 Analysis can be run reproducibly using documentation provided in the README

- [ ] Usage documentation could be improved for clarity (i.e., it is not explicitly clear to the user how to use the project, or some of the wording is confusing). **-2** **writing**
**Comment:**: Missing EDA script in usage. Images in the reports are generated from Rmd so it needs to be run before producing the report.

- [ ] Could not reproducibly run the analysis because the code fails. **-5** **accuracy**
**Comment:** There was some issues running docopt, I think it requires a space between Options and Usage in the documentation section. Make sure to run it to confirm it works. The commands in the readme usage should be in root working directory (command for predictions.py is in "src" working directory). Also the output of clean.py is LLCP2015_clean.csv but input of  predictions.py is LLCP2015_cleaned.csv. Make sure to rerun the whole analysis from scratch using the commands in usage to make sure you documented everything you did in the analysis.

### 4. Submission expectations

- [ ] Please provide the link to the release as `https://github.com/UBC-MDS/REPOSITORY/tree/VERSION` (replacing `REPOSITORY` and `VERSION` with the correct ones for your project version for each milestone). This makes is a lot easier for someone to just visit the repository as it was at that point in the project's history. **-1** **mechanics**
 
### Other comments
- [ ] Make sure you include all the code used to generate figures in the report. I am not able to find how you generated bmi.png and age.png from the four scripts. 
- [ ] Fix formatting issues in final report (ie Table 3 column name, sub-heading of document )
